services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - .env

    ecommerce:
        build: .
        container_name: django-ecommerce
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DEBUG: ${DEBUG}
            DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
            DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
            DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
            DATABASE_ENGINE: ${DATABASE_ENGINE}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
        env_file:
            - .env
        volumes:
            - ecommerce_static:/app/staticfiles
            - ecommerce_media:/app/media

volumes:
    postgres_data:
    ecommerce_static:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/www/ppm/staticfiles
    ecommerce_media:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/www/ppm/media