# Generated by Django 5.2.3 on 2025-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In attesa di Pagamento"),
                    ("paid", "Pagato"),
                    ("processing", "In Elaborazione"),
                    ("shipped", "Spedito"),
                    ("completed", "Completato"),
                    ("cancelled", "Annullato"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
