# Generated by Django 5.2.3 on 2025-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_created_product_image_product_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
